name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test ${{ github.workspace }}/AnimalAdoption.Web.Portal.UnitTests/AnimalAdoption.Web.Portal.UnitTests.csproj --no-build --verbosity normal    

    - name: Publish .NET
      run: dotnet publish ${{ github.workspace }}/AnimalAdoption.Web.Portal/AnimalAdoption.Web.Portal.csproj --no-build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: webportal
        path: ${{github.workspace }}/AnimalAdoption.Web.Portal/bin/Debug/netcoreapp3.1/publish/

  deployTest:
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: 'team2-env'
      url: ${{ steps.deploy-to-webapp-test.outputs.webapp-url }}

    env:
        APP_SERVICE_NAME: 'team2-tta'

    steps: 
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: webportal
      
      - name: Azure Login     
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZ_CRD }}'

      - name: Azure Keyvalut
        uses: Azure/get-keyvault-secret@v1
        with:
          keyvault: "team2-TTA"
          secrets: 'Globalpassword'
        id: myGetSecetAction



      - name: Settings Azure web Service 
        uses: Azure/appservice-settings@v1
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          app-settings-json: '[{"name": "GlobalPassword","value": "${{ steps.myGetSecetAction.outputs.Globalpassword","slotSetting": false}]'


      - name: Deploy to Azure Web App
        id: deploy-to-webapp-test
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          # publish-profile: ${{ secrets.TEAM2_WEB_PUBLISH }}
          pakage: .

    